name: finalpbb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  qr_flutter: ^4.1.0
  cloud_functions: ^5.5.1
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.6
  firebase_crashlytics: ^4.3.7
  firebase_analytics: ^11.5.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos-fineshi.png" 