name: Build Flutter Android App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.7.2
      - run: flutter upgrade
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle